
package com.ftn.banka;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;

/**
 * This class was generated by Apache CXF 2.6.5
 * 2018-02-13T18:47:35.795+01:00
 * Generated source version: 2.6.5
 * 
 */
public final class Banka_Banka_Client {

    private static final QName SERVICE_NAME = new QName("http://www.ftn.com/banka", "BankaService");

    private Banka_Banka_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = BankaService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        BankaService ss = new BankaService(wsdlURL, SERVICE_NAME);
        Banka port = ss.getBanka();  
        
        {
        System.out.println("Invoking clearSettleBanka...");
        com.ftn.schema.mt102.Mt102 _clearSettleBanka_mt102 = null;
        com.ftn.schema.mt910.Mt910 _clearSettleBanka_mt910 = null;
        port.clearSettleBanka(_clearSettleBanka_mt102, _clearSettleBanka_mt910);


        }
        {
        System.out.println("Invoking slanjeNalogaZaPlacanje...");
        com.ftn.schema.prenos.NalogZaPrenos _slanjeNalogaZaPlacanje_nalog = null;
        boolean _slanjeNalogaZaPlacanje__return = port.slanjeNalogaZaPlacanje(_slanjeNalogaZaPlacanje_nalog);
        System.out.println("slanjeNalogaZaPlacanje.result=" + _slanjeNalogaZaPlacanje__return);


        }
        {
        System.out.println("Invoking preuzimanjeIzvoda...");
        com.ftn.schema.zahtev.ZahtevZaIzvod _preuzimanjeIzvoda_zahtev = null;
        com.ftn.schema.izvod.Izvod _preuzimanjeIzvoda__return = port.preuzimanjeIzvoda(_preuzimanjeIzvoda_zahtev);
        System.out.println("preuzimanjeIzvoda.result=" + _preuzimanjeIzvoda__return);


        }
        {
        System.out.println("Invoking rtgsBanka...");
        com.ftn.schema.mt103.Mt103 _rtgsBanka_mt103 = null;
        com.ftn.schema.mt910.Mt910 _rtgsBanka_mt910 = null;
        port.rtgsBanka(_rtgsBanka_mt103, _rtgsBanka_mt910);


        }

        System.exit(0);
    }

}
