
package com.ftn.narodna_banka;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 2.6.5
 * 2018-02-13T19:04:02.607+01:00
 * Generated source version: 2.6.5
 * 
 */
 
public class NarodnaBanka_NarodnaBanka_Server{

    protected NarodnaBanka_NarodnaBanka_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new NarodnaBankaImpl();
        String address = "http://localhost:8080/narodna_banka";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new NarodnaBanka_NarodnaBanka_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
